import React, { useState, useEffect } from 'react';
import { MockService } from '../../services/mockService';
import { User, UniqueCode } from '../../types';
import { CheckCircle, Plus, Users, GraduationCap, Clock, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const AdminDashboard: React.FC = () => {
    const [pendingUsers, setPendingUsers] = useState<User[]>([]);
    const [codes, setCodes] = useState<UniqueCode[]>([]);
    const [stats, setStats] = useState({
        students: 0,
        faculty: 0,
        pending: 0
    });

    useEffect(() => {
        refreshData();
    }, []);

    const refreshData = async () => {
        const pending = await MockService.getPendingUsers();
        const allStudents = await MockService.getStudents({ includePending: true });
        const allFaculty = await MockService.getFaculty();
        const allCodes = await MockService.getCodes();

        setPendingUsers(pending);
        setCodes(allCodes);
        setStats({
            students: allStudents.length,
            faculty: allFaculty.length,
            pending: pending.length
        });
    };

    const handleApprove = async (id: string) => {
        await MockService.approveUser(id);
        refreshData();
    };

    const handleGenerateCode = async (role: 'student' | 'faculty') => {
        await MockService.generateCode(role, `Generated by Admin on ${new Date().toLocaleDateString()}`);
        refreshData();
    };

    const handleDeleteCode = async (id: string) => {
        if (confirm('Are you sure you want to delete this code?')) {
            await MockService.deleteCode(id);
            refreshData();
        }
    };

    return (
        <div>
            <div className="flex justify-between items-center mb-6">
                <h1 className="text-2xl font-bold text-slate-800 dark:text-white">Dashboard Overview</h1>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <Link to="/admin/students" className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-blue-100 dark:bg-blue-900 rounded-lg text-blue-600 dark:text-blue-300">
                        <Users className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Total Students</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.students}</h3>
                    </div>
                </Link>
                <Link to="/admin/faculty" className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-purple-100 dark:bg-purple-900 rounded-lg text-purple-600 dark:text-purple-300">
                        <GraduationCap className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Total Faculty</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.faculty}</h3>
                    </div>
                </Link>
                <div className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4">
                    <div className="p-3 bg-yellow-100 dark:bg-yellow-900 rounded-lg text-yellow-600 dark:text-yellow-300">
                        <Clock className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Pending Approvals</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.pending}</h3>
                    </div>
                </div>
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                {/* Pending Approvals */}
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white">Pending Registrations</h2>
                        <span className="text-sm text-slate-500 dark:text-slate-400">{pendingUsers.length} requests</span>
                    </div>
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
                        {pendingUsers.length === 0 ? (
                            <div className="p-8 text-center text-slate-500 dark:text-slate-400">No pending student registrations.</div>
                        ) : (
                            <div className="divide-y divide-slate-100 dark:divide-slate-700">
                                {pendingUsers.map(u => (
                                    <div key={u.id} className="p-4 hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                                        <div className="flex justify-between items-start">
                                            <div>
                                                <p className="font-medium text-slate-800 dark:text-white">{u.fullName}</p>
                                                <p className="text-xs text-slate-500 dark:text-slate-400">{u.course} • {u.department}</p>
                                                <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">{u.email}</p>
                                            </div>
                                            <button
                                                onClick={() => handleApprove(u.id)}
                                                className="text-green-600 hover:text-green-700 p-1"
                                                title="Approve"
                                            >
                                                <CheckCircle className="w-5 h-5" />
                                            </button>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>

                {/* Registration Codes */}
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white">Registration Codes</h2>
                        <div className="flex gap-2">
                            <button onClick={() => handleGenerateCode('student')} className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-3 py-1 rounded-lg hover:bg-blue-200 dark:hover:bg-blue-800 transition-colors">
                                + Student
                            </button>
                            <button onClick={() => handleGenerateCode('faculty')} className="text-xs bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300 px-3 py-1 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-800 transition-colors">
                                + Faculty
                            </button>
                        </div>
                    </div>
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden max-h-[400px] overflow-y-auto">
                        <table className="w-full text-left">
                            <thead className="bg-slate-50 dark:bg-slate-700 border-b border-slate-200 dark:border-slate-600 sticky top-0">
                                <tr>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase">Code</th>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase">Role</th>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase">Status</th>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                                {[...codes].reverse().map(c => (
                                    <tr key={c.id}>
                                        <td className="px-4 py-3 font-mono text-xs text-slate-800 dark:text-white">{c.code}</td>
                                        <td className="px-4 py-3 text-xs capitalize text-slate-600 dark:text-slate-300">{c.role}</td>
                                        <td className="px-4 py-3">
                                            {c.isUsed ? (
                                                <span className="text-[10px] bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300 px-2 py-0.5 rounded-full">Used</span>
                                            ) : (
                                                <span className="text-[10px] bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300 px-2 py-0.5 rounded-full">Active</span>
                                            )}
                                        </td>
                                        <td className="px-4 py-3 text-right">
                                            {!c.isUsed && (
                                                <button
                                                    onClick={() => handleDeleteCode(c.id)}
                                                    className="text-red-500 hover:text-red-700 text-xs font-medium"
                                                >
                                                    Delete
                                                </button>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default AdminDashboard;
