import React, { useState, useEffect } from 'react';
import { MockService } from '../../services/mockService';
import { User, UniqueCode } from '../../types';
import { CheckCircle, Plus, Users, GraduationCap, Clock, ShieldCheck, Copy, UserCog, FileText, Calendar, Eye, Trash2 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';

const AdminDashboard: React.FC = () => {
    const navigate = useNavigate();
    const [pendingUsers, setPendingUsers] = useState<User[]>([]);
    const [codes, setCodes] = useState<UniqueCode[]>([]);
    const [stats, setStats] = useState({
        students: 0,
        faculty: 0,
        pending: 0,
        profileRequests: 0
    });

    const [notification, setNotification] = useState<string | null>(null);

    useEffect(() => {
        refreshData();
    }, []);

    const showNotification = (message: string) => {
        setNotification(message);
        setTimeout(() => setNotification(null), 3000);
    };

    const refreshData = async () => {
        const pending = await MockService.getPendingUsers();
        const allStudents = await MockService.getStudents(true);
        const allFaculty = await MockService.getFaculty();
        const allCodes = await MockService.getCodes();
        const profileRequests = await MockService.getProfileUpdateRequests();

        setPendingUsers(pending);
        setCodes(allCodes);
        setStats({
            students: allStudents.length,
            faculty: allFaculty.length,
            pending: pending.length,
            profileRequests: profileRequests.length
        });
    };

    const handleApprove = async (id: string) => {
        await MockService.approveUser(id);
        showNotification('User approved successfully');
        refreshData();
    };

    const handleGenerateCode = async (role: 'student' | 'faculty') => {
        await MockService.generateCode(role, `Generated by Admin on ${new Date().toLocaleDateString()}`);
        showNotification(`${role === 'student' ? 'Student' : 'Faculty'} registration code generated successfully!`);
        refreshData();
    };

    const handleDeleteCode = async (id: string) => {
        if (confirm('Are you sure you want to delete this code?')) {
            await MockService.deleteCode(id);
            showNotification('Registration code deleted');
            refreshData();
        }
    };

    const [selectedCodeUser, setSelectedCodeUser] = useState<any>(null);

    const handleCodeClick = (code: UniqueCode) => {
        if (code.isUsed) {
            if (code.usedBy) {
                if (code.role === 'student') {
                    navigate('/admin/students', { state: { viewUserId: code.usedBy.id } });
                } else if (code.role === 'faculty') {
                    navigate('/admin/faculty', { state: { viewUserId: code.usedBy.id } });
                }
            } else {
                alert("User details are not available. The user account might have been deleted.");
            }
        }
    };

    return (
        <div>
            <div className="flex justify-between items-center mb-6">
                <h1 className="text-2xl font-bold text-slate-800 dark:text-white">Dashboard Overview</h1>
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
                <Link to="/admin/students" className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-blue-100 dark:bg-blue-900 rounded-lg text-blue-600 dark:text-blue-300">
                        <Users className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Total Students</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.students}</h3>
                    </div>
                </Link>
                <Link to="/admin/faculty" className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-purple-100 dark:bg-purple-900 rounded-lg text-purple-600 dark:text-purple-300">
                        <GraduationCap className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Total Faculty</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.faculty}</h3>
                    </div>
                </Link>
                <Link to="/admin/requests" className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-yellow-100 dark:bg-yellow-900 rounded-lg text-yellow-600 dark:text-yellow-300">
                        <Clock className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Pending Approvals</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.pending}</h3>
                    </div>
                </Link>
                <Link to="/admin/requests" state={{ activeTab: 'updates' }} className="bg-white dark:bg-slate-800 p-6 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 flex items-center space-x-4 hover:shadow-md transition-shadow cursor-pointer">
                    <div className="p-3 bg-indigo-100 dark:bg-indigo-900 rounded-lg text-indigo-600 dark:text-indigo-300">
                        <UserCog className="w-6 h-6" />
                    </div>
                    <div>
                        <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Profile Requests</p>
                        <h3 className="text-2xl font-bold text-slate-800 dark:text-white">{stats.profileRequests}</h3>
                    </div>
                </Link>
            </div>

            <div className="grid grid-cols-1 gap-8">


                {/* Registration Codes */}
                <div className="space-y-4">
                    <div className="flex justify-between items-center">
                        <h2 className="text-lg font-semibold text-slate-800 dark:text-white">Registration Codes</h2>
                        <div className="flex gap-2">
                            <button onClick={() => handleGenerateCode('student')} className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-700 dark:text-blue-300 px-3 py-1 rounded-lg hover:bg-blue-200 dark:hover:bg-blue-800 transition-colors">
                                + Student
                            </button>
                        </div>
                    </div>
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden max-h-[600px] overflow-y-auto">
                        <table className="w-full text-left">
                            <thead className="bg-slate-50 dark:bg-slate-700 border-b border-slate-200 dark:border-slate-600 sticky top-0 z-10">
                                <tr>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase w-1/6">Code</th>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase">Status / Details</th>
                                    <th className="px-4 py-3 text-xs font-semibold text-slate-500 dark:text-slate-300 uppercase text-right w-1/6">Action</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-100 dark:divide-slate-700">
                                {codes.map(c => (
                                    <tr key={c.id}>
                                        <td className="px-4 py-3 font-mono text-xs text-slate-800 dark:text-white align-top">
                                            <div className="flex items-center gap-2">
                                                <span
                                                    className={c.isUsed ? "cursor-pointer hover:text-blue-600 underline decoration-dotted" : ""}
                                                    onClick={() => handleCodeClick(c)}
                                                    title={c.isUsed ? "Click to view user details" : "Copy code"}
                                                >
                                                    {c.code}
                                                </span>
                                                <button
                                                    onClick={() => {
                                                        navigator.clipboard.writeText(c.code);
                                                        showNotification('Code copied to clipboard!');
                                                    }}
                                                    className="text-slate-400 hover:text-blue-500 transition-colors"
                                                    title="Copy Code"
                                                >
                                                    <Copy className="w-3 h-3" />
                                                </button>
                                            </div>
                                        </td>
                                        <td className="px-4 py-3 align-top">
                                            {c.isUsed ? (
                                                <div className="flex items-start gap-4">
                                                    <span className="shrink-0 inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-medium bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300 mt-1">
                                                        Used
                                                    </span>
                                                    {c.usedBy ? (
                                                        <div className="flex-1 min-w-0">
                                                            <div className="flex flex-wrap items-baseline gap-2 mb-1.5">
                                                                <span className="text-sm font-semibold text-slate-900 dark:text-white">{c.usedBy.fullName}</span>
                                                                <span className="text-xs text-slate-500 dark:text-slate-400">({c.usedBy.email})</span>
                                                            </div>
                                                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-1 text-xs text-slate-600 dark:text-slate-300">
                                                                {c.usedBy.collegeRollNo && (
                                                                    <div className="flex gap-1">
                                                                        <span className="text-slate-400 dark:text-slate-500">Roll:</span>
                                                                        <span className="font-medium">{c.usedBy.collegeRollNo}</span>
                                                                    </div>
                                                                )}
                                                                {c.usedBy.department && (
                                                                    <div className="flex gap-1">
                                                                        <span className="text-slate-400 dark:text-slate-500">Dept:</span>
                                                                        <span className="font-medium">{c.usedBy.department}</span>
                                                                    </div>
                                                                )}
                                                                {c.usedBy.course && (
                                                                    <div className="flex gap-1">
                                                                        <span className="text-slate-400 dark:text-slate-500">Course:</span>
                                                                        <span className="font-medium">{c.usedBy.course}</span>
                                                                    </div>
                                                                )}
                                                                {c.usedBy.mobile && (
                                                                    <div className="flex gap-1">
                                                                        <span className="text-slate-400 dark:text-slate-500">Ph:</span>
                                                                        <span className="font-medium">{c.usedBy.mobile}</span>
                                                                    </div>
                                                                )}
                                                                {c.usedBy.fatherName && (
                                                                    <div className="flex gap-1 col-span-full">
                                                                        <span className="text-slate-400 dark:text-slate-500">Father:</span>
                                                                        <span className="font-medium">{c.usedBy.fatherName}</span>
                                                                    </div>
                                                                )}
                                                            </div>
                                                        </div>
                                                    ) : (
                                                        <span className="text-xs text-slate-400 italic mt-1">User details unavailable</span>
                                                    )}
                                                </div>
                                            ) : (
                                                <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-medium bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300">
                                                    Active
                                                </span>
                                            )}
                                        </td>
                                        <td className="px-4 py-3 align-top text-right">
                                            <div className="flex items-center justify-end gap-2">
                                                {c.isUsed && (
                                                    <button
                                                        onClick={() => handleCodeClick(c)}
                                                        className="p-1.5 text-blue-600 hover:bg-blue-50 dark:hover:bg-blue-900/30 rounded-lg transition-colors"
                                                        title="View User Details"
                                                    >
                                                        <Eye className="w-4 h-4" />
                                                    </button>
                                                )}
                                                <button
                                                    onClick={() => handleDeleteCode(c.id)}
                                                    className="p-1.5 text-red-600 hover:bg-red-50 dark:hover:bg-red-900/30 rounded-lg transition-colors"
                                                    title="Delete Code"
                                                >
                                                    <Trash2 className="w-4 h-4" />
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            {/* Notification Toast */}
            {notification && (
                <div className="fixed top-6 right-6 z-50 animate-bounce-in">
                    <div className="bg-white/90 dark:bg-slate-800/90 backdrop-blur-md border border-green-200 dark:border-green-900 text-slate-800 dark:text-white px-6 py-4 rounded-2xl shadow-2xl flex items-center space-x-4 min-w-[320px]">
                        <div className="bg-green-100 dark:bg-green-900/50 p-2 rounded-full">
                            <CheckCircle className="w-6 h-6 text-green-600 dark:text-green-400" />
                        </div>
                        <div>
                            <h4 className="font-bold text-sm">Success</h4>
                            <p className="text-sm text-slate-600 dark:text-slate-300">{notification}</p>
                        </div>
                    </div>
                </div>
            )}

            {/* User Details Modal */}
            {selectedCodeUser && (
                <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
                    <div className="bg-white dark:bg-slate-800 rounded-xl shadow-xl w-full max-w-md overflow-hidden animate-bounce-in">
                        <div className="p-6 border-b border-slate-100 dark:border-slate-700 flex justify-between items-center">
                            <h3 className="text-lg font-bold text-slate-800 dark:text-white">Code Usage Details</h3>
                            <button onClick={() => setSelectedCodeUser(null)} className="text-slate-400 hover:text-slate-600">
                                <span className="sr-only">Close</span>
                                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                            </button>
                        </div>
                        <div className="p-6 text-center">
                            <div className="w-20 h-20 bg-blue-100 dark:bg-blue-900 rounded-full flex items-center justify-center mx-auto mb-4 text-blue-600 dark:text-blue-300 text-3xl font-bold">
                                {selectedCodeUser.fullName.charAt(0)}
                            </div>
                            <h4 className="text-xl font-bold text-slate-800 dark:text-white mb-1">{selectedCodeUser.fullName}</h4>
                            <p className="text-slate-500 dark:text-slate-400 mb-4">{selectedCodeUser.email}</p>

                            <div className="bg-slate-50 dark:bg-slate-700/50 rounded-lg p-4 text-left text-sm space-y-2">
                                <div className="flex justify-between border-b border-slate-200 dark:border-slate-600 pb-2">
                                    <span className="text-slate-500 dark:text-slate-400">User ID:</span>
                                    <span className="font-mono text-slate-700 dark:text-slate-300 text-xs">{selectedCodeUser.id || selectedCodeUser._id}</span>
                                </div>
                                {selectedCodeUser.collegeRollNo && (
                                    <div className="flex justify-between">
                                        <span className="text-slate-500 dark:text-slate-400">Roll No:</span>
                                        <span className="font-medium text-slate-700 dark:text-slate-300">{selectedCodeUser.collegeRollNo}</span>
                                    </div>
                                )}
                                {selectedCodeUser.course && (
                                    <div className="flex justify-between">
                                        <span className="text-slate-500 dark:text-slate-400">Course:</span>
                                        <span className="font-medium text-slate-700 dark:text-slate-300">{selectedCodeUser.course}</span>
                                    </div>
                                )}
                                {selectedCodeUser.department && (
                                    <div className="flex justify-between">
                                        <span className="text-slate-500 dark:text-slate-400">Department:</span>
                                        <span className="font-medium text-slate-700 dark:text-slate-300">{selectedCodeUser.department}</span>
                                    </div>
                                )}
                                {(selectedCodeUser.year || selectedCodeUser.semester) && (
                                    <div className="flex justify-between">
                                        <span className="text-slate-500 dark:text-slate-400">Year/Sem:</span>
                                        <span className="font-medium text-slate-700 dark:text-slate-300">{selectedCodeUser.year} / {selectedCodeUser.semester}</span>
                                    </div>
                                )}
                                {selectedCodeUser.mobile && (
                                    <div className="flex justify-between">
                                        <span className="text-slate-500 dark:text-slate-400">Mobile:</span>
                                        <span className="font-medium text-slate-700 dark:text-slate-300">{selectedCodeUser.mobile}</span>
                                    </div>
                                )}
                            </div>
                        </div>
                        <div className="p-4 bg-slate-50 dark:bg-slate-700/50 text-right">
                            <button
                                onClick={() => setSelectedCodeUser(null)}
                                className="px-4 py-2 bg-slate-200 dark:bg-slate-700 text-slate-800 dark:text-white rounded-lg hover:bg-slate-300 dark:hover:bg-slate-600 transition-colors"
                            >
                                Close
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};
export default AdminDashboard;
