import React, { useState, useEffect } from 'react';
import { MockService } from '../../services/mockService';
import { User, UniqueCode } from '../../types';
import { CheckCircle, XCircle, Plus, Copy } from 'lucide-react';
import FacultyDashboard from '../faculty/FacultyDashboard';
import EventManager from '../../components/EventManager';

const AdminDashboard: React.FC = () => {
  const [pendingUsers, setPendingUsers] = useState<User[]>([]);
  const [codes, setCodes] = useState<UniqueCode[]>([]);
  const [activeTab, setActiveTab] = useState<'approvals' | 'codes' | 'faculty' | 'calendar'>('approvals');

  useEffect(() => {
    refreshData();
  }, []);

  const refreshData = async () => {
    setPendingUsers(await MockService.getPendingUsers());
    setCodes(await MockService.getCodes());
  };

  const handleApprove = async (id: string) => {
    await MockService.approveUser(id);
    refreshData();
  };

  const handleGenerateCode = async (role: 'student' | 'faculty') => {
    await MockService.generateCode(role, `Generated by Admin on ${new Date().toLocaleDateString()}`);
    refreshData();
  };

  return (
    <div>
        <h1 className="text-2xl font-bold text-slate-800 mb-6">Admin Panel</h1>

        <div className="flex space-x-4 border-b border-slate-200 mb-6">
            <button 
                onClick={() => setActiveTab('approvals')}
                className={`pb-3 px-1 text-sm font-medium ${activeTab === 'approvals' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500'}`}
            >
                Pending Approvals ({pendingUsers.length})
            </button>
            <button 
                onClick={() => setActiveTab('codes')}
                className={`pb-3 px-1 text-sm font-medium ${activeTab === 'codes' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500'}`}
            >
                Unique Registration Codes
            </button>
            <button 
                onClick={() => setActiveTab('faculty')}
                className={`pb-3 px-1 text-sm font-medium ${activeTab === 'faculty' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500'}`}
            >
                Faculty Dashboard
            </button>
            <button 
                onClick={() => setActiveTab('calendar')}
                className={`pb-3 px-1 text-sm font-medium ${activeTab === 'calendar' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-slate-500'}`}
            >
                Calendar
            </button>
        </div>

        {activeTab === 'approvals' && (
            <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                {pendingUsers.length === 0 ? (
                    <div className="p-8 text-center text-slate-500">No pending student registrations.</div>
                ) : (
                    <table className="w-full text-left">
                         <thead className="bg-slate-50 border-b border-slate-200">
                            <tr>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Name</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Details</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Email</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {pendingUsers.map(u => (
                                <tr key={u.id}>
                                    <td className="px-6 py-4 font-medium text-slate-800">{u.fullName}</td>
                                    <td className="px-6 py-4 text-sm text-slate-600">{u.course} - {u.department} ({u.year})</td>
                                    <td className="px-6 py-4 text-sm text-slate-600">{u.email}</td>
                                    <td className="px-6 py-4 text-right">
                                        <button 
                                            onClick={() => handleApprove(u.id)}
                                            className="inline-flex items-center text-green-600 hover:text-green-700 font-medium text-sm"
                                        >
                                            <CheckCircle className="w-4 h-4 mr-1" /> Approve
                                        </button>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>
        )}

        {activeTab === 'codes' && (
             <div className="space-y-6">
                <div className="flex gap-4">
                    <button onClick={() => handleGenerateCode('student')} className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg text-sm flex items-center">
                        <Plus className="w-4 h-4 mr-2" /> Generate Student Code
                    </button>
                    <button onClick={() => handleGenerateCode('faculty')} className="bg-slate-800 hover:bg-slate-900 text-white px-4 py-2 rounded-lg text-sm flex items-center">
                         <Plus className="w-4 h-4 mr-2" /> Generate Faculty Code
                    </button>
                </div>

                <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
                     <table className="w-full text-left">
                         <thead className="bg-slate-50 border-b border-slate-200">
                            <tr>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Code</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Role</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Status</th>
                                <th className="px-6 py-4 text-xs font-semibold text-slate-500 uppercase">Notes</th>
                            </tr>
                        </thead>
                         <tbody className="divide-y divide-slate-100">
                            {[...codes].reverse().map(c => (
                                <tr key={c.id}>
                                    <td className="px-6 py-4 font-mono text-sm text-slate-800">{c.code}</td>
                                    <td className="px-6 py-4 text-sm capitalize text-slate-600">{c.role}</td>
                                    <td className="px-6 py-4">
                                        {c.isUsed ? (
                                            <span className="text-xs bg-red-100 text-red-800 px-2 py-1 rounded-full">Used</span>
                                        ) : (
                                            <span className="text-xs bg-green-100 text-green-800 px-2 py-1 rounded-full">Active</span>
                                        )}
                                    </td>
                                    <td className="px-6 py-4 text-sm text-slate-500">{c.createdFor}</td>
                                </tr>
                            ))}
                        </tbody>
                     </table>
                </div>
             </div>
        )}

        {activeTab === 'faculty' && (
            <div className="bg-slate-50 border border-dashed border-slate-200 rounded-xl p-4">
                <FacultyDashboard />
            </div>
        )}

        {activeTab === 'calendar' && (
            <EventManager
                title="Institution Calendar"
                description="Add or curate institute-wide events and reminders."
                canCreate
                allowAllActions
            />
        )}
    </div>
  );
};

export default AdminDashboard;
